export default{
    home: '/',
    login: '/login',
    signup:'/signup',
    profile: '/profile',
    profileUpdate: '/profile/update',
    gsignin:'/google/signin',
    courses:"/courses",
    course:"/course",
    courseDetails:"/course/details",
    chapterDetails:"/chapter/details",
    chaptersList:"/chapter/list",
    dashboard:"/dashboard",
    marks:"/marks",
    chat:"/chat/user",
    community:"/community/user",
    payments:"/payments",
    paymentHistory:"/payments/history",
    videomeet:"/videomeet",
    videomeetJoin:"/join/videomeet",
    myCourse:"/course",
    getChatHistory:"/chat/history",
    getOtp:"/otp",
    getOtpForReset:"/otp/reset",
    resentOtp:"/resend-otp",
    sendEmail:"/sent/email",
    enterEmail:"/forgot/password",
    enterEmailPost:"/forgot/password",
    newPassword:"/newpassword",
    newPasswordPost:"/newpassword",
    notFound:"/*"
    
}

